backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Yazılar / Makaleler"
    folder: "_posts"
    create: true
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Yayın Tarihi", name: "date", widget: "datetime"}
      - {label: "Etiket", name: "tag", widget: "select", options: ["Ceza Hukuku", "Gayrimenkul", "İş Hukuku", "Aile Hukuku", "Veraset", "Şirketler Hukuku", "Genel"]}
      - {label: "İçerik", name: "body", widget: "markdown"}